# Generated by Django 5.1.1 on 2024-09-08 06:52

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0003_alter_subscription_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=225, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=225, null=True, unique=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, max_length=225, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='content_image/')),
                ('video', models.FileField(blank=True, null=True, upload_to='content_video/')),
                ('like', models.IntegerField(blank=True, default=0, null=True)),
                ('dislike', models.IntegerField(blank=True, default=0, null=True)),
                ('forward', models.IntegerField(blank=True, default=0, null=True)),
                ('premiere_date', models.DateField(blank=True, null=True)),
                ('language', models.CharField(blank=True, choices=[('en', 'English'), ('ru', 'Russian'), ('uz', 'Uzbek')], max_length=225, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_content', to='common.category')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel_content', to='common.channel')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_content', to='common.country')),
                ('play_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='play_list_content', to='common.playlist')),
                ('tags', models.ManyToManyField(blank=True, to='common.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
