# Generated by Django 5.1.1 on 2024-09-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0006_premiera'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_short_video',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
