# Generated by Django 5.1.1 on 2024-09-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0007_content_is_short_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
