# Generated by Django 5.1.1 on 2024-09-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_bio_user_description_user_adress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='adress',
            field=models.TextField(blank=True, max_length=225, null=True),
        ),
    ]
