# Generated by Django 5.1.1 on 2024-09-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='adress',
            field=models.TextField(blank=True, null=True),
        ),
    ]
