# Generated by Django 5.1.1 on 2024-09-08 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_subemail_alter_subscription_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_channel', to='common.channel'),
        ),
    ]
